typography_spectrum: 0.22590787871740758
color:
  brandStrength: 0.11197599722072482
  lightness: 0.8631152473390102
  saturation: 0.9654685684945434
  rhythmicContrast: 0.3749016826041043
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.07300220686011016
name: NadraSofea
title: Pocket Full Of Sunshine
description: the adventure begins
